remote_theme: PaulSt/eleven
theme: eleven-theme

eleven:
  date_format: "%b %d, %Y"
  logo:  "assets/logo.png"

permalink: post/:title

title: "Steinblog"
description: ""
excerpt_separator: <!--more-->
page_excerpts: true

collections:
  Harz:
    output: true

baseurl: /steinblog
