name: ci

on:
  push:
    branches: [main]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global http.postBuffer 524288000
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:                               
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'
